# Generated by Django 6.0 on 2026-02-01 06:30

import apps.persons.models
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=200)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('death_place', models.CharField(blank=True, max_length=200, null=True)),
                ('is_living', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.persons.models.person_photo_path)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_persons', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='families.family')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['first_name', 'last_name'], name='person_name_gin', opclasses=['gin_trgm_ops', 'gin_trgm_ops']), models.Index(fields=['family'], name='persons_per_family__9400b5_idx'), models.Index(fields=['last_name'], name='persons_per_last_na_eb9bbc_idx'), models.Index(fields=['gender'], name='persons_per_gender_0bd275_idx'), models.Index(fields=['created_at'], name='persons_per_created_49082b_idx')],
            },
        ),
    ]
