# Generated by Django 6.0 on 2026-03-15 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='person',
            name='person_name_gin',
        ),
    ]
