# Generated by Django 6.0 on 2025-12-24 06:33

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0004_remove_joinrequest_approved_joinrequest_status'),
        ('persons', '0002_person_created_by_person_death_place_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='person',
            index=django.contrib.postgres.indexes.GinIndex(fields=['first_name', 'last_name'], name='person_name_gin', opclasses=['gin_trgm_ops', 'gin_trgm_ops']),
        ),
    ]
