# Generated by Django 5.0 on 2025-11-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='code',
            field=models.CharField(db_column='family_code', db_index=True, max_length=12, unique=True),
        ),
    ]
