# Generated by Django 5.0 on 2025-11-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_alter_family_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='code',
            field=models.CharField(db_index=True, max_length=12, unique=True),
        ),
    ]
