# Generated by Django 5.0 on 2025-11-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0003_alter_family_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinrequest',
            name='approved',
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
