# Generated by Django 5.0 on 2025-11-22 09:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0004_remove_joinrequest_approved_joinrequest_status'),
        ('persons', '0002_person_created_by_person_death_place_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('parent', 'Parent'), ('child', 'Child'), ('spouse', 'Spouse')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_relationships', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='families.family')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='persons.person')),
                ('related_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='persons.person')),
            ],
            options={
                'unique_together': {('person', 'related_person', 'relationship_type')},
            },
        ),
    ]
